import {StyleSheet} from 'react-native';

import {Colors} from 'shared/libs/helpers/colors';

export const ProfileStyles = StyleSheet.create({
  scrollContainer: {
    flexGrow: 1,
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  container: {
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 200,
    paddingBottom: 20,
  },
  image_teamIT: {
    position: 'absolute',
    top: 60,
    right: 50,
    width: 0,
    height: 0,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0)',
  },
  add_image__button: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#D9D9D9',
    top: 90,
    width: 125,
    height: 125,
    borderRadius: 100,
    marginTop: 11,
    marginBottom: 13,
  },
  add_image__text: {
    fontFamily: 'Inter-Regular',
    fontSize: 48,
    color: '#FFFFFF',
  },
  selectedImage: {
    width: 125,
    height: 125,
    borderRadius: 100,
  },
  container1: {
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  closeButton: {
    position: 'absolute',
    top: 40,
    right: 80,
    width: 20,
    height: 325,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0)',
  },
  exitButton: {
    position: 'absolute',
    top: 42,
    right: 50,
    width: 20,
    height: 325,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0)',
  },
  project__about__container: {
    width: 274,
    marginTop: 5,
  },
  project__about__text: {
    fontSize: 18,
    color: '#000000',
    fontFamily: 'Inter-Medium',
    fontWeight: '500',
    textAlign: 'center',
  },
  profileDataContainer: {
    width: '100%',
    marginTop: 20,
    paddingHorizontal: 20,
  },
  text: {
    position: 'absolute',
    top: 245,
    marginHorizontal: -500,
    fontSize: 22,
    color: '#333',
    fontFamily: 'Inter-Regular',
  },
  background_image: {
    position: 'absolute',
    justifyContent: 'center',
    backgroundColor: '#BE9DE8',
    top: -50,
    width: 500,
    height: 225,
    marginTop: 11,
    marginBottom: 13,
  },
  selectedBackgroundImage: {
    width: 500,
    height: 225,
  },
  invite: {
    position: 'absolute',
    top: 275,
    backgroundColor: '#BE9DE8',
    width: 200,
    height: 40,
    borderRadius: 10,
    marginTop: 10,
  },
  inviteProject: {
    color: '#FFFFFF',
    top: 7,
    fontSize: 18,
    textAlign: 'center',
  },
  backselectedImage: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    top: 90,
    width: 133,
    height: 133,
    borderRadius: 100,
  },
});
