import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
  },
  modalContent: {
    width: 316,
    maxHeight: '91.25%',
    backgroundColor: 'white',
    padding: 20,
    borderRadius: 30,
    alignItems: 'center',
  },
  modalTitle: {
    fontSize: 27,
    fontFamily: 'Inter-Bold',
    fontWeight: 'bold',
  },
  scrollViewContainer: {
    flexGrow: 1,
    alignItems: 'center',
    paddingBottom: 20,
  },
  closeButton: {
    marginLeft: '90%',
    marginTop: 5,
    width: 20,
    height: 20,
    alignItems: 'flex-end',
    justifyContent: 'flex-end',
  },
  add_image__button: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#D9D9D9',
    width: 64,
    height: 75,
    borderRadius: 20,
    marginTop: 11,
    marginBottom: 13,
  },
  add_image__text: {
    fontFamily: 'Inter-Regular',
    fontSize: 48,
    color: '#FFFFFF',
  },
  project_name__placeholder: {
    backgroundColor: '#EDEDED',
    fontSize: 18,
    fontFamily: 'Inter-Medium',
    fontWeight: '500',
    color: '#A8A8A8',
    borderRadius: 30,
    paddingVertical: 9,
    paddingHorizontal: 18,
    width: 274,
    height: 42,
  },
  project_name__placeholder_about: {
    backgroundColor: '#EDEDED',
    fontSize: 18,
    fontFamily: 'Inter-Medium',
    fontWeight: '500',
    color: '#A8A8A8',
    borderRadius: 30,
    paddingVertical: 9,
    paddingHorizontal: 18,
    width: 274,
    minHeight: 100,
    maxHeight: 185,
    alignItems: 'flex-start',
    alignSelf: 'flex-start',
    textAlignVertical: 'top',
  },
  project__about__container: {
    width: 274,
    minHeight: 100,
  },
  project__text: {
    fontFamily: 'Inter-SemiBold',
    fontSize: 18,
    marginLeft: 12,
    marginTop: 15,
    marginBottom: 10,
  },
  project__text_2: {
    fontFamily: 'Inter-SemiBold',
    fontSize: 18,
    marginTop: 15,
    marginBottom: 10,
  },
  project__container_with_plus: {
    alignItems: 'flex-start',
    alignSelf: 'flex-start',
    marginLeft: 12,
  },
  fdrow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 15,
    margin: 0,
  },
  project__button_plus: {
    backgroundColor: '#BE9DE8',
    width: 34,
    height: 21,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 20,
    color: '#FFFFFF',
  },
  plus1: {
    fontSize: 24,
    color: '#FFFFFF',
    marginTop: -5,
  },
  plus2: {
    marginTop: -5.5,
    marginLeft: 5,
    fontSize: 16,
    color: '#C7C7C7',
  },

  project__button_create: {
    backgroundColor: '#9260D1',
    width: 177,
    height: 46,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 85,
  },
  project__text_create: {
    fontFamily: 'Inter-Bold',
    fontSize: 18,
    color: '#FFFFFF',
  },
  selectedImage: {
    width: 64,
    height: 75,
    borderRadius: 20,
  },
  selectedItemsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 15,
    flexWrap: 'wrap',
  },
  selectedItem: {
    backgroundColor: '#BE9DE8',
    borderRadius: 20,
    flexDirection: 'row',
    alignItems: 'center',
    height: 21,
    paddingVertical: 3,
    paddingHorizontal: 5,
  },
  selectedItemText: {
    color: 'white',
    fontFamily: 'Inter-SemiBold',
    fontSize: 12,
  },
  removeSelectedItem: {
    marginLeft: 5,
  },
  removeSelectedItemTextContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
  },
  cross1: {
    fontSize: 24,
    color: '#C7C7C7',
    marginTop: -7,
    marginLeft: 7.5,
    transform: [{rotate: '45deg'}],
  },
  cross2: {
    marginTop: -4,
    marginLeft: 7.5,
    fontSize: 16,
    color: '#C7C7C7',
    transform: [{rotate: '45deg'}],
  },
  removeSelectedItemText: {
    color: '#BBBBBB',
    textAlign: 'center',
  },
  dropdownContainer: {
    position: 'relative',
    maxHeight: 150,
    width: 160,
    backgroundColor: '#BE9DE8',
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 15,
    zIndex: 999,
    marginTop: 15,
  },
  dropdownWrapper: {
    paddingTop: 13,
    paddingLeft: 6,
    paddingRight: 13,
    paddingBottom: 5,
  },
  dropdownItem: {
    marginBottom: 10,
    color: 'white',
    fontFamily: 'Inter-SemiBold',
  },
  dropdownItem_icon: {
    width: 20,
    height: 10,
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    marginTop: 2.5,
  },
  dropdownItemContainer: {
    display: 'flex',
    flex: 1,
    paddingLeft: 11,
    flexDirection: 'row',
  },
  dropdownItemText: {
    marginLeft: 5,
    color: 'white',
    fontFamily: 'Inter-SemiBold',
    fontSize: 12,
  },
  dropdownItemSelected: {
    //backgroundColor: '#F2F2F2',
  },
  skillsInputContainer: {
    width: 274,
    marginBottom: 16,
  },
  skillsInput: {
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 8,
    padding: 10,
    marginBottom: 8,
  },
  selectedSkillsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 10,
  },
  skillPill: {
    backgroundColor: '#dedede',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 20,
  },
  skillPillText: {
    color: '#333',
  },
  skillsDropdown: {
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 8,
    backgroundColor: 'white',
    maxHeight: 150,
  },
  skillDropdownItem: {
    padding: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
});
