export const categories = [
    //{key:'1', value:'ПИВО'},
    {key:'2', value:'Desktop'},
    {key:'3', value:'Мобильные'},
    {key:'4', value:'Web'},
    {key:'5', value:'Магазины'},
    {key:'6', value:'Соц.сети'},
    {key:'7', value:'Игры'},
    {key:'8', value:'Учебные'},
    {key:'9', value:'Консольные'},
    {key:'10', value:'Нативные'},
    {key:'11', value:'Кроссплатформенные'},
    {key:'12', value:'VR'},
    {key:'13', value:'Онлайн-сервис'},
    {key:'14', value:'Промо-прилож.'},
    {key:'15', value:'Встроенные'},
    {key:'16', value:'Чат-бот'},
]